name: publish

on:
  push:
    tags:
      - "v*.*.*"

env:
  draft: true

jobs:
  build-windows:
    runs-on: windows-latest
    name: ${{ matrix.config.target }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        config:
        - {target: wasm3-win-x64,   platform: "-A x64",     toolset: "-T ClangCL"   }
        - {target: wasm3-win-x86,   platform: "-A Win32",   toolset: "-T ClangCL"   }

    env:
      LDFLAGS: -s
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.config.platform }} ${{ matrix.config.toolset }} ..
    - name: Build
      run: |
        cmake --build build --config Release
        cp ./build/Release/wasm3.exe ./${{ matrix.config.target }}.exe
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: ${{ env.draft }}
        files: "*.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-cosmopolitan:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Build αcτµαlly pδrταblε εxεcµταblε
      run: |
        cd platforms/cosmopolitan
        ./build.sh
        cp ./wasm3.com ../../wasm3-cosmopolitan.com
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: ${{ env.draft }}
        files: "*.com"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-wasi:
    runs-on: ubuntu-latest
    name: wasm3-wasi
    timeout-minutes: 10

    env:
      LDFLAGS: -s
    steps:
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        python3 -m pip install pip==20.1.1
        python3 -m pip install --upgrade setuptools wheel
        pip3 --version
    - name: Install Wasienv
      env:
        WASMER_RELEASE_TAG: "1.0.1"
      run: curl https://raw.githubusercontent.com/wasienv/wasienv/master/install.sh | sh
    - name: Configure
      run: |
        source $HOME/.wasienv/wasienv.sh
        mkdir build
        cd build
        wasimake cmake -DBUILD_WASI=metawasi ..
    - name: Build
      run: |
        source $HOME/.wasienv/wasienv.sh
        cmake --build build
        cp ./build/wasm3.wasm ./wasm3-wasi.wasm
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: ${{ env.draft }}
        files: "*.wasm"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    name: wasm3-android-tests
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: |
        sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
    - name: Build
      run: |
        cd platforms/android
        ./gradlew build
    - name: Copy
      run: |
        cp ./platforms/android/app/build/outputs/apk/debug/app-debug.apk ./wasm3-android-test.apk
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        draft: ${{ env.draft }}
        files: "*.apk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
